version: "3"

services:
  database:
    image: mysql:8.0
    container_name: mysql-issue-tracker
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=issue-tracker
      - MYSQL_ROOT_PASSWORD=team-30
      - TZ=Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
