version: "3"

services:
  database:
    container_name: mysql-container
    image: mysql:8.0.22
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=test
      - TZ=Asia/Seoul

