spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/issuetracker
    username: donggi
    password: '0614'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    defer-datasource-initialization: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
