const GREYSCALE = {
  OFF_WHITE: '#FEFEFE',
  BACKGROUND: '#F7F7FC',
  INPUT_BACKGROUND: '#EFF0F6',
  LINE: '#D9DBE9',
  PLACEHOLDER: '#A0A3BD',
  LABEL: '#6E7191',
  BODY: '#4E4B66',
  TITLE_ACTION: '#14142B',
};

export default GREYSCALE;
