spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/testdb
    password: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    codesquad.backend:
      issuetracker: debug

oauth:
  github:
    client_id: a062f7e1bd2cefcb3157
    client_secret: ${GITHUB_CLIENT_SECRET}

auth:
  jwt:
    secret_key: ${JWT_SECRET_KEY}
