spring:
  datasource:
    url: jdbc:mysql://issue-tracker-db1.clbw75mv0xha.ap-northeast-2.rds.amazonaws.com/issue_tracker
    username: admin
    password: ${MYSQL_PASSWORD}

oauth2:
  credentials:
    github:
      redirect-path: http://localhost:8081/github-callback
      client-id: 25d03cdad594202b186e
      client-secret: ${GITHUB_OAUTH_CLIENT_SECRET}
