spring:
  config:
    activate:
      on-profile: local


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/testdb
    username: root
    password: test

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  logging.level:
    org.hibernate.SQL: debug

s3:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  bucket-name: ${BUCKET_NAME}
  region: ${REGION}

cloud:
  aws:
    region:
      static: ${REGION}
    stack:
      auto: false

