spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: mysql
    defer-datasource-initialization: true # 추후 초기화 데이터 삽입용

logging.level:
  org.hibernate.SQL: debug
  com.airbnb: debug
