spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3308/issue_tracker?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

oauth2:
  github:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

logging:
  level.kr.codesquad.issuetracker: debug
